[versions]
agp = "7.4.2"
android-viewbinding = "1.0.4"
coil = "2.4.0"
coreSplashscreen = "1.0.1"
cryptoreVersion = "1.4.0"
calendarVersion = "3.0.0"
circleIndicatorVersion = "2.1.6"
exoplayerPlayer = "1.1.0"
graphVersion = "v3.1.0"
glide = "4.15.1"
hilt-android = "2.47"
kotlin = "1.9.0"
core-ktx = "1.10.1"
data-store="1.0.0"
appcompat = "1.6.1"
kotlinxCoroutinesAndroid = "1.7.1"
lifecycleExtensions = "2.2.0"
lifecycleRuntimeKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
firebase-bom = "32.2.0"
markdownViewVersion = "1.1.1"
navigation-safe-args-gradle-plugin = "2.6.0"
navigation-ui = "2.6.0"
playServicesAds = "22.2.0"
recycler-view = "1.3.1-rc01"
retrofit-version = "2.9.0"
gson-version = "2.10.1"
lottiVersion = "6.1.0"
browser = "1.5.0"
roomCompiler = "2.5.2"
roomKtx = "2.5.2"
palette_version = "28.0.0"
play-service-auth = "20.6.0"
playstorecore = "1.8.1"


[libraries]
android-viewbinding = { module = "com.github.yogacp:android-viewbinding", version.ref = "android-viewbinding" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
cryptore = { group = "com.kazakago.cryptore", name = "cryptore", version.ref = "cryptoreVersion" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "exoplayerPlayer" }
exoplayer-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayerPlayer" }
exoplayer-core = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayerPlayer" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
calender = { group = "com.github.sundeepk", name = "compact-calendar-view", version.ref = "calendarVersion" }
circle-indicator = { group = "me.relex", name = "circleindicator", version.ref = "circleIndicatorVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
data-store = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "data-store" }
firebase-bom= { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-config-ktx = { group = "com.google.firebase", name = "firebase-config-ktx" }
graph = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "graphVersion" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson-version" }
markDownView = { group = "com.github.mukeshsolanki", name = "MarkdownView-Android", version.ref = "markdownViewVersion" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args-gradle-plugin" }
navigation-common-ktx = { module = "androidx.navigation:navigation-common-ktx", version.ref = "navigation-ui" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-ui" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-ui" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
recycler-view = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recycler-view" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit-version" }
retrofit-json = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit-version" }
retrofit-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit-version" }
lotti = { group = "com.airbnb.android", name = "lottie", version.ref = "lottiVersion" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
palette = { group = "com.android.support", name = "palette-v7", version.ref = "palette_version" }
play-service-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-service-auth" }
playstore-core = { group = "com.google.android.play", name = "core-ktx", version.ref = "playstorecore" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

[bundles]

