name: Release Info

on:
  push:
    branches:
      - master
jobs:
  Generated:
    runs-on: ubuntu-latest
    steps:
      - uses: joutvhu/get-release@v1
        id: latest_release
        with:
          latest: true
          pattern: 'pre.+'
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
      - name: Print Details
        run: |
          echo release ${{ steps.latest_release.outputs.tag_name }}